name: phrase
description: Phrase Strings over-the-air translations library for Flutter
version: 1.1.0
homepage: https://phrase.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  yaml: ^3.1.0
  shared_preferences: ^2.0.5
  path: ^1.8.0
  path_provider: ^2.0.1
  crypto: ^3.0.1
  uuid: ^3.0.4
  http: ^0.13.3
  package_info_plus: ^3.1.1
  synchronized: ^3.0.0
  glob: ^2.0.1
  build: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.4
  build_runner: ^2.1.5
  test: ^1.14.4
